services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "30432:5432"

  nilchain:
    image: ghcr.io/nillionnetwork/nilchain-devnet:v0.1.0
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "30648:26648" # JSON RPC

  nilauth:
    image: public.ecr.aws/k5d9x2g2/nilauth:latest
    depends_on:
      - db
      - nilchain
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ${NILAUTH_CONFIG_FILE:-./config.test.yaml}:/opt/config.yaml
    command: ["--config-file", "/opt/config.yaml"]
    ports:
      - "30921:30921" # main server
      - "39022:39022" # metrics server

  token-price-api:
    image: caddy:2
    ports:
      - "30923:80"
    command: |
      caddy respond --listen :80 --body '{"nillion":{"usd":1}}' --header "Content-Type: application/json" 
