name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: mise run build
      - run: mise run check

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: mise run test-coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          comment-on: "pr"
